version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/appuser/app
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 2; echo "Try to connect";  done; uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres_data:
